# Site settings
title: くもキャスト
email: your-email@domain.com
description: 独学でプログラミングを学ぶ若者たちがゆるくつながってお話をしています
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kumocast.jp" # the base hostname & protocol for your site
twitter_username: kumocast
github_username:  jekyll

members:
  gaaamii:
    icon: https://avatars1.githubusercontent.com/u/4538656?v=3&s=80
  karur4n:
    icon: https://avatars2.githubusercontent.com/u/6816398?v=3&s=80
  yoshiso44:
    icon: https://avatars3.githubusercontent.com/u/3690884?v=3&s=80
  _ayato_p:
    icon: https://avatars3.githubusercontent.com/u/1432156?v=3&s=80
  kimihito:
    icon: https://avatars2.githubusercontent.com/u/758704?v=3&s=80

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap"]
